name: Benchmark
on:
  push: {}
  workflow_dispatch: {}
  
permissions:
  contents: read
  id-token: write

jobs:
  build-with-docker:
    name: Build with Docker
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: docker/setup-buildx-action@v1
      - name: Save start time
        run: echo $(date +%s) > starttime.txt
      - uses: docker/build-push-action@v2
        with:
          context: ./upstream
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Save start time
        run: cat starttime.txt
      - name: ls
        run: ls